### ISSUE TITLE
Load System with ASDF instead of Swank

### ISSUE THREAD

**Issue by Symbolics** [incjung/cl-swagger-codegen#4]
More than likely, instead of:

`swank:operate-on-system-for-emacs`

people will use

`asdf:load-system "<system-name>" for loading`

swank functions are intended to be used by Swank/Slime, not directly at the REPL. It looks as if the code will support this, but the documentation (README) instructs users to use swank.

**Comment by incjung** [comment]
Ah. I see. 
After some tests, I would update it.
Thank you.
